name: CI - Deploy to CloudHub
 
on:
  push:
    branches:
      - main
 
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
 
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
 
      - name: Set up Maven settings.xml
        run: |
          mkdir -p ~/.m2
          cat <<EOF > ~/.m2/settings.xml
          <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                                        https://maven.apache.org/xsd/settings-1.0.0.xsd">
            <servers>
              <server>
                <id>anypoint-exchange-v3</id>
                <username>~~~Client~~~</username>
                <password>130445978d5744eebe6fa58adf035819~?~5e409E38a99B4162B56B044A0FA0CD57</password>
              </server>
            </servers>
          </settings>
          EOF
 
      - name: Deploy to CloudHub
        run: mvn clean deploy -DmuleDeploy -Danypoint.environment=Sandbox -s /home/runner/.m2/settings.xml